version: "3"


services:


  web:
    container_name: likes_web
    build:
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    command: >
              sh -c "python3 manage.py makemigrations &&
              python3 manage.py migrate &&
              python3 manage.py runserver 0.0.0.0:8000"